[tool.poetry]
name = "financial-portfolio-manager"
version = "0.1.0"
description = ""
authors = ["kenk67 <rahulmg1899i@gmail.com>"]
readme = "README.md"
packages = [{include = "financial_portfolio_manager"}]

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.10.1"
numpy = "^2.2.5"
pandas = "^2.2.3"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
black = "^25.1.0"
flake8 = "^7.2.0"
pydantic = "^2.11.4"
pydantic-settings = "^2.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
